version: "3"

services:
  senacHistory_db:
    image: mariadb
    container_name: senacHistory_db
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_DATABASE=senacMyhistory
      - MYSQL_ROOT_PASSWORD=s3nacHlst0ry
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
  senacHistory_web:
    image: webdevops/php-nginx:8.2
    container_name: senacHistory_web
    ports:
      - "80:80"
    links:
      - senacHistory_db
    volumes:
      - ./public/:/var/www/html
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/html/
      - PHP_MEMORY_LIMIT=1G